import numpy as np
from scipy.interpolate import interp1d


class Interpolator:
    """
    A class to interpolate RHS values generated by RandomFunctionGenerator
    over a given domain, allowing the evaluation of RHS at any arbitrary point.

    Attributes
    ----------
    domain : np.ndarray
        The domain over which the RHS is defined.
    rhs_values : np.ndarray
        The values of the RHS generated by RandomFunctionGenerator.
    interpolator : Callable[[float], float]
        A callable object that interpolates the RHS values.

    Methods
    -------
    __init__(domain: np.ndarray, rhs_values: np.ndarray)
        Initializes the RHSInterpolator with the given domain and RHS values.
    evaluate(x: Union[float, np.ndarray]) -> Union[float, np.ndarray]
        Evaluates the interpolated RHS at a given point or array of points.
    """

    def __init__(self, domain: np.ndarray, rhs_values: np.ndarray):
        """
        Initializes the RHSInterpolator class.

        Parameters
        ----------
        domain : np.ndarray
            The domain over which the RHS is defined.
        rhs_values : np.ndarray
            The values of the RHS corresponding to the domain points.

        Raises
        ------
        ValueError
            If the domain and rhs_values arrays are of unequal length.
        """
        if len(domain) != len(rhs_values):
            raise ValueError("Domain and RHS values must have the same length.")

        # Store the domain and RHS values
        self.domain = domain
        self.rhs_values = rhs_values

        # Create an interpolator using linear interpolation
        self.interpolator = interp1d(
            domain, rhs_values, kind="linear", fill_value="extrapolate"
        )

    def evaluate(self, x: np.ndarray) -> np.ndarray:
        """
        Evaluates the interpolated RHS at specified points.

        Parameters
        ----------
        x : np.ndarray
            The points at which to evaluate the interpolated RHS.

        Returns
        -------
        np.ndarray
            The interpolated RHS values at the specified points.

        Notes
        -----
        The interpolation is linear, and values outside the domain are extrapolated.
        """
        return self.interpolator(x)
